<a href="https://colab.research.google.com/github/Kush0319/Project-8/blob/main/Project_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

class DataAnalytics:
    project_name = "NumPy Analyzer Toolkit"

    def __init__(self):
        """Constructor to initialize the main array."""
        self.main_array = None

    @classmethod
    def display_project_info(cls):
        """Class method to display project info."""
        print(f"\n--- {cls.project_name} ---")

    @staticmethod
    def print_separator():
        """Static method for UI formatting utility."""
        print("========================================")

    def __is_array_created(self):
        """Private method to encapsulate the check for an existing array."""
        if self.main_array is None:
            print("\nPlease create an array first (Option 1)!")
            return False
        return True

    def create_array(self):
        print("\nSelect the type of array to create:")
        print("1. 1D Array\n2. 2D Array\n3. 3D Array")
        choice = input("Enter your choice: ")

        try:
            if choice == '1':
                n = int(input("Enter the number of elements: "))
                elements = input(f"Enter {n} elements separated by space: ").split()
                self.main_array = np.array([int(x) for x in elements])

            elif choice == '2':
                rows = int(input("Enter the number of rows: "))
                cols = int(input("Enter the number of columns: "))
                elements = input(f"Enter {rows * cols} elements separated by space: ").split()
                self.main_array = np.array([int(x) for x in elements]).reshape(rows, cols)

            elif choice == '3':
                depth = int(input("Enter the depth (number of matrices): "))
                rows = int(input("Enter the number of rows: "))
                cols = int(input("Enter the number of columns: "))
                elements = input(f"Enter {depth * rows * cols} elements separated by space: ").split()
                self.main_array = np.array([int(x) for x in elements]).reshape(depth, rows, cols)
            else:
                print("Invalid choice.")
                return

            print("\nArray created successfully:")
            print(self.main_array)
        except ValueError:
            print("Error: Please ensure you enter the correct number of integer elements.")

    def mathematical_operations(self):
        if not self.__is_array_created(): return

        print("\nChoose a mathematical operation:")
        print("1. Addition\n2. Subtraction\n3. Multiplication\n4. Division\n5. Dot Product (2D only)")
        op_choice = input("Enter your choice: ")

        try:
            print(f"\nOriginal Array:\n{self.main_array}")
            elements = input("Enter the same-size array elements (separated by space): ").split()
            second_array = np.array([int(x) for x in elements]).reshape(self.main_array.shape)
            print(f"\nSecond Array:\n{second_array}")

            if op_choice == '1':
                print(f"\nResult of Addition:\n{np.add(self.main_array, second_array)}")
            elif op_choice == '2':
                print(f"\nResult of Subtraction:\n{np.subtract(self.main_array, second_array)}")
            elif op_choice == '3':
                print(f"\nResult of Multiplication:\n{np.multiply(self.main_array, second_array)}")
            elif op_choice == '4':
                print(f"\nResult of Division:\n{np.divide(self.main_array, second_array)}")
            elif op_choice == '5':
                if self.main_array.ndim == 2:
                    print(f"\nResult of Dot Product:\n{np.dot(self.main_array, second_array)}")
                else:
                    print("Dot product requires 2D arrays.")
            else:
                print("Invalid choice.")
        except Exception as e:
            print(f"Error performing operation: {e}. Ensure dimensions match.")

    def combine_or_split(self):
        if not self.__is_array_created(): return

        print("\nChoose an option:\n1. Combine Arrays\n2. Split Array")
        choice = input("Enter your choice: ")

        if choice == '1':
            elements = input("Enter elements of another array to combine (space separated): ").split()
            try:
                second_array = np.array([int(x) for x in elements]).reshape(self.main_array.shape)
                combined = np.vstack((self.main_array, second_array))
                print(f"\nCombined Array (Vertical Stack):\n{combined}")
            except ValueError:
                print("Dimensions must match to combine.")

        elif choice == '2':
            splits = int(input("Enter number of equal splits: "))
            try:
                split_arrays = np.array_split(self.main_array, splits)
                for i, arr in enumerate(split_arrays):
                    print(f"\nSplit {i+1}:\n{arr}")
            except Exception as e:
                print(f"Error splitting array: {e}")

    def search_sort_filter(self):
        if not self.__is_array_created(): return
        print("\nChoose an option:\n1. Search a value\n2. Sort the array\n3. Filter values")
        choice = input("Enter your choice: ")
        print(f"\nOriginal Array:\n{self.main_array}")
        if choice == '1':
            val = int(input("Enter value to search: "))
            indices = np.where(self.main_array == val)
            print(f"Value found at indices: {indices}")
        elif choice == '2':
            sorted_arr = np.sort(self.main_array, axis=None)
            print(f"\nSorted Array (Ascending):\n{sorted_arr}")
        elif choice == '3':
            condition = int(input("Enter a value to filter elements greater than: "))
            filtered = self.main_array[self.main_array > condition]
            print(f"\nFiltered Array (Elements > {condition}):\n{filtered}")

    def aggregates_and_statistics(self):
        if not self.__is_array_created(): return
        print("\nChoose an operation:\n1. Sum\n2. Mean\n3. Median\n4. Standard Deviation\n5. Variance")
        print("6. Minimum and Maximum\n7. Percentiles\n8. Correlation Coefficient")
        choice = input("Enter your choice: ")
        print(f"\nOriginal Array:\n{self.main_array}")
        if choice == '1': print(f"Sum: {np.sum(self.main_array)}")
        elif choice == '2': print(f"Mean: {np.mean(self.main_array)}")
        elif choice == '3': print(f"Median: {np.median(self.main_array)}")
        elif choice == '4': print(f"Standard Deviation: {np.std(self.main_array)}")
        elif choice == '5': print(f"Variance: {np.var(self.main_array)}")
        elif choice == '6': print(f"Min: {np.min(self.main_array)}, Max: {np.max(self.main_array)}")
        elif choice == '7':
            p = int(input("Enter percentile (0-100): "))
            print(f"{p}th Percentile: {np.percentile(self.main_array, p)}")
        elif choice == '8':
            if self.main_array.ndim == 2:
                print(f"Correlation Coefficient:\n{np.corrcoef(self.main_array)}")
            else:
                print("Correlation requires a 2D array.")

In [2]:
analyzer = DataAnalytics()
DataAnalytics.display_project_info()
DataAnalytics.print_separator()
print("Welcome to the NumPy Analyzer!")
DataAnalytics.print_separator()

while True:
    print("\nChoose an option:")
    print("1. Create a Numpy Array")
    print("2. Perform Mathematical Operations")
    print("3. Combine or Split Arrays")
    print("4. Search, Sort, or Filter Arrays")
    print("5. Compute Aggregates and Statistics")
    print("6. Exit")
    choice = input("Enter your choice: ")
    if choice == '1':
        analyzer.create_array()
    elif choice == '2':
        analyzer.mathematical_operations()
    elif choice == '3':
        analyzer.combine_or_split()
    elif choice == '4':
        analyzer.search_sort_filter()
    elif choice == '5':
        analyzer.aggregates_and_statistics()
    elif choice == '6':
        print("\nThank you for using the NumPy Analyzer! Goodbye!")
        break
    else:
        print("\nInvalid input. Please choose a number from 1 to 6.")


--- NumPy Analyzer Toolkit ---
Welcome to the NumPy Analyzer!

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
Enter your choice: 1

Select the type of array to create:
1. 1D Array
2. 2D Array
3. 3D Array
Enter your choice: 1
Enter the number of elements: 5
Enter 5 elements separated by space: 1 2 3 4 5

Array created successfully:
[1 2 3 4 5]

Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
Enter your choice: 2

Choose a mathematical operation:
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Dot Product (2D only)
Enter your choice: 1

Original Array:
[1 2 3 4 5]
Enter the same-size array elements (separated by space): 5 4 3 2 1

Second Array:
[5 4 3 2 1]

Result of Addition:
[6 6 6 6 6]

Choose an option:
1